### ISSUE TITLE
Need timer

### ISSUE THREAD

**Issue by SWolfMN78** [Wolfknightx/GrpPro12-2#1]
This is where we can collect information about using the timer class in c#

**Comment by FreeMasen** [comment]
https://msdn.microsoft.com/en-us/library/system.timers.timer(v=vs.110).aspx

**Comment by FreeMasen** [comment]
https://msdn.microsoft.com/en-us/library/system.timers.timer(v=vs.110).aspx

**Comment by SWolfMN78** [comment]
This is where I found the information on formatting the time information.  Enjoy!!
https://msdn.microsoft.com/en-us/library/8kb3ddd4%28v=vs.110%29.aspx
