### ISSUE TITLE
im having issues with the sync command its not giving me the update

### ISSUE THREAD

**Issue by Nappyd326648** [Wolfknightx/GrpPro12-2#6]

**Comment by FreeMasen** [comment]
What kind of an error are you getting?

**Comment by Nappyd326648** [comment]
it says theirs isnt any thing to sync but i dont see any of the teams changes in my version

**Comment by FreeMasen** [comment]
Are you syncing through the github app or vs?

**Comment by Nappyd326648** [comment]
github

**Comment by SWolfMN78** [comment]
Where you two able to get the information loaded up to GitHub?  I got the timer up and going.  Either we'll touch base in class on our next moves or  feel free to hit me up either here or on text.  612-408-6654 with next moves.

**Comment by rmasen** [comment]
I was able to get the sln file to download.  Right now we are missing come key pieces to get us to our next working point.  I am not sure that the Timer is set up properly, the interval is set to 0.1 seconds (this could cause some problems with memory) and there is a property that defines if the timer elapsed event can be called more than once, we need to make sure that this is set propertly.

In addition in our oTickets class we have 3 methods, add, remove, and reset; all of these are recursively calling themselves, they will for sure cause an issue if this is not setup properly.  There is a good example on page 445 of our book.  This can be used as a reference but note that the author has modified the add behavior and we don't want to do that, also the logic for resetting the list will not be listed here.
