### ISSUE TITLE
validator class

### ISSUE THREAD

**Issue by FreeMasen** [Wolfknightx/GrpPro12-2#8]

**Comment by SWolfMN78** [comment]
This item may have to be designed after we have leveled out everything else.  This would insure that we have a "happy" path and I can write the validation code around the pitfalls.

Thoughts?

**Comment by FreeMasen** [comment]
Well, our controls are pretty much set now that you were able to get the datetime picker to work properly.  Looking at the current set of controls that I see on the options form, we could really remove any need for a textbox.  Each of them can be up/down based controls and we could set the lower limit on any non-time controls to be 1, so that we don't try and create a window with 0 tickets.  I think this is better than implementing the validator class.
